### ISSUE TITLE
Issue with running Tutorial step6_part4.py

### ISSUE THREAD

**Issue by Abhivega** [httk/httk#33]
On execution, the Traceback reads:
```
    Traceback (most recent call last):
      File "step6_part4.py", line 30, in <module>
        for rundir, computation in reader:
      File "/home/abhijith/work/httk/src/httk/task/reader.py", line 76, in reader
        manifest_dir(dirpath, manifestfile, os.path.join(dirpath, 'ht.config'), keydir, sk, pk, force=force_remake_manifests)
      File "/home/abhijith/work/httk/src/httk/core/crypto.py", line 219, in manifest_dir
        manifestfile.write(pubkey+"\n")
      File "/home/abhijith/anaconda3/lib/python3.7/bz2.py", line 241, in write
        compressed = self._compressor.compress(data)
    TypeError: a bytes-like object is required, not 'str'
```
Python version :
3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0]

**Comment by hpleva** [comment]
This is caused by some left-over Python3 compatibility bugs.
I have submitted a PR #34 that should fix the issue.

**Comment by Abhivega** [comment]
Thanks.
